name: cd-pipeline

on:
  push:
    branches:
      - main

jobs:
  cd_pipeline:
    runs-on: self-hosted
    steps:
      - name: Deploy Application
        working-directory: /root/bookmark-deployment
        run: |
          echo "Deploying application..."
          # Update the local deployment files on the VM
          git pull origin main
          
          # Clean up unused/dangling resources
          docker system prune -f
          
          # Pull latest Docker image tags specified in docker-compose.yaml
          docker compose pull
          
          # Recreate containers with the new image
          docker compose up -d
          
          